name: 'pharma_spend_dashboard'
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.12
    - pandas=2.2
    - altair=5.3
    - ipykernel
    - altair-all
    - dash
    - dash-bootstrap-components
    - plotly
    - geopandas=1.0.*
    - tabulate  # df.to_markdown()
    - lxml  # pd.read_html()
    - pip=24.0
    - pip:
        - dash-vega-components
        - vegafusion==1.6.9
        - vegafusion-python-embed==1.6.9
        - Flask==2.2.2
        - flask_caching==2.3.1
        - Werkzeug==2.2.2
        - pytest==8.3.5